"""reconcile models with initial schema

Revision ID: 069df939229f
Revises: 58e9278aee5a
Create Date: 2026-03-20 02:49:02.955843

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import FetchedValue
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '069df939229f'
down_revision = '58e9278aee5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biometric_verifications', schema=None) as batch_op:
        batch_op.create_index('idx_biometric_verifications_location', ['location'], unique=False, postgresql_using='gist')

    with op.batch_alter_table('contractor_credentials', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('contractor_devices', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint('contractor_devices_contractor_id_device_id_key', type_='unique')
        batch_op.create_unique_constraint('unique_contractor_device', ['contractor_id', 'device_id'])

    with op.batch_alter_table('contractor_insurance', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('contractor_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_duration_minutes', sa.Integer(), server_default=FetchedValue(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('contractors', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index('idx_contractors_email')
        batch_op.create_index('idx_contractors_email', ['email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))

    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_contractor_id', sa.UUID(), nullable=True))
        batch_op.alter_column('contractor_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.create_index('idx_issues_issue_reported_location', ['issue_reported_location'], unique=False, postgresql_using='gist')
        batch_op.drop_constraint('issues_contractor_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('issues_assigned_contractor_id_fkey', 'contractors', ['assigned_contractor_id'], ['contractor_id'])
        batch_op.create_foreign_key('issues_contractor_id_fkey', 'contractors', ['contractor_id'], ['contractor_id'])

    with op.batch_alter_table('job_assignments', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('job_completions', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint('job_completions_job_id_contractor_id_key', type_='unique')
        batch_op.create_index('idx_job_completions_job_completed_location', ['job_completed_location'], unique=False, postgresql_using='gist')
        batch_op.create_unique_constraint('job_completions_job_id_key', ['job_id'])

    with op.batch_alter_table('job_responses', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint('job_responses_job_id_contractor_id_key', type_='unique')
        batch_op.create_index('idx_job_responses_job_accepted_location', ['job_accepted_location'], unique=False, postgresql_using='gist')
        batch_op.create_unique_constraint('unique_job_contractor_response', ['job_id', 'contractor_id'])

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.create_index('idx_jobs_job_location_geography', ['job_location_geography'], unique=False, postgresql_using='gist')

    with op.batch_alter_table('local_sync_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.create_index('idx_photos_photo_location', ['photo_location'], unique=False, postgresql_using='gist')

    # Drop views that depend on completion_percentage_after (generated column)
    op.execute("DROP VIEW IF EXISTS job_status_summary CASCADE;")

    with op.batch_alter_table('progress_updates', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # Drop columns with CASCADE since completion_percentage_after is a
    # generated column that depends on completion_percentage and
    # completion_percentage_before.  CASCADE will also drop the generated
    # completion_percentage_after column.
    op.execute(
        "ALTER TABLE progress_updates "
        "DROP COLUMN IF EXISTS completion_percentage CASCADE;"
    )
    op.execute(
        "ALTER TABLE progress_updates "
        "DROP COLUMN IF EXISTS completion_percentage_before CASCADE;"
    )

    # Re-add completion_percentage_after as a regular (non-generated) column.
    # The model treats it as a server-computed value via FetchedValue().
    op.execute(
        "ALTER TABLE progress_updates "
        "ADD COLUMN completion_percentage_after INTEGER DEFAULT 0;"
    )

    # Recreate job_status_summary view
    op.execute("""
        CREATE OR REPLACE VIEW job_status_summary AS
        WITH latest_progress AS (
            SELECT DISTINCT ON (job_id)
                job_id,
                completion_percentage_after,
                created_at as last_progress_update
            FROM progress_updates
            ORDER BY job_id, created_at DESC
        )
        SELECT
            j.job_id,
            j.job_number,
            j.job_name,
            j.job_description,
            j.status,
            j.priority,
            j.scheduled_start_date,
            j.scheduled_end_date,
            j.actual_start_date,
            j.actual_end_date,
            j.job_type,
            j.job_category,
            j.vendor_name,
            j.site_address_city as site_city,
            j.site_address_state as site_state,
            COUNT(DISTINCT ja.contractor_id) as assigned_contractors,
            COUNT(DISTINCT sv.visit_id) as total_visits,
            MAX(sv.check_in_time) as last_check_in,
            COUNT(DISTINCT i.issue_id) FILTER (
                WHERE i.issue_status NOT IN ('resolved', 'closed')
            ) as open_issues,
            COALESCE(lp.completion_percentage_after, 0)
                as current_completion_percentage,
            COUNT(DISTINCT t.task_id) FILTER (
                WHERE t.task_status != 'completed'
            ) as pending_tasks,
            COUNT(DISTINCT t.task_id) as total_tasks,
            CASE
                WHEN jc.job_completed THEN 'Completed'
                WHEN j.actual_start_date IS NOT NULL THEN 'In Progress'
                ELSE 'Not Started'
            END as progress_status,
            jc.vendor_confirmed,
            jc.vendor_confirmed_at,
            j.vendor_sync_status
        FROM jobs j
        LEFT JOIN job_assignments ja ON j.job_id = ja.job_id
            AND ja.assignment_status = 'active'
        LEFT JOIN site_visits sv ON j.job_id = sv.job_id
        LEFT JOIN issues i ON j.job_id = i.job_id
        LEFT JOIN tasks t ON j.job_id = t.job_id
        LEFT JOIN job_completions jc ON j.job_id = jc.job_id
        LEFT JOIN latest_progress lp ON j.job_id = lp.job_id
        WHERE j.deleted_at IS NULL
        GROUP BY j.job_id, j.job_number, j.job_name, j.job_description,
                 j.status, j.priority, j.scheduled_start_date,
                 j.scheduled_end_date, j.actual_start_date,
                 j.actual_end_date, j.job_type, j.job_category,
                 j.vendor_name, j.site_address_city, j.site_address_state,
                 jc.job_completed, lp.completion_percentage_after,
                 lp.last_progress_update, jc.vendor_confirmed,
                 jc.vendor_confirmed_at, j.vendor_sync_status;
    """)

    with op.batch_alter_table('site_visits', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.create_index('idx_site_visits_check_in_location', ['check_in_location'], unique=False, postgresql_using='gist')
        batch_op.create_index('idx_site_visits_check_out_location', ['check_out_location'], unique=False, postgresql_using='gist')

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.create_index('idx_submissions_submitted_location', ['submitted_location'], unique=False, postgresql_using='gist')

    with op.batch_alter_table('task_executions', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('vendor_sync_queue', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('vendor_sync_queue', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('task_executions', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index('idx_submissions_submitted_location', postgresql_using='gist')
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('site_visits', schema=None) as batch_op:
        batch_op.drop_index('idx_site_visits_check_out_location', postgresql_using='gist')
        batch_op.drop_index('idx_site_visits_check_in_location', postgresql_using='gist')
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('progress_updates', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # Drop the view that references completion_percentage_after
    op.execute("DROP VIEW IF EXISTS job_status_summary CASCADE;")
    # Recreate the original columns and generated column
    op.execute(
        "ALTER TABLE progress_updates "
        "ADD COLUMN completion_percentage_before percent_value;"
    )
    op.execute(
        "ALTER TABLE progress_updates "
        "ADD COLUMN completion_percentage percent_value NOT NULL "
        "DEFAULT 0;"
    )
    # Drop the standalone completion_percentage_after, recreate as generated
    op.execute(
        "ALTER TABLE progress_updates "
        "DROP COLUMN IF EXISTS completion_percentage_after;"
    )
    op.execute(
        "ALTER TABLE progress_updates "
        "ADD COLUMN completion_percentage_after percent_value "
        "GENERATED ALWAYS AS ("
        "LEAST(completion_percentage_before + completion_percentage, 100)"
        ") STORED;"
    )
    # Recreate the original view with generated column
    op.execute("""
        CREATE OR REPLACE VIEW job_status_summary AS
        WITH latest_progress AS (
            SELECT DISTINCT ON (job_id)
                job_id,
                completion_percentage_after,
                created_at as last_progress_update
            FROM progress_updates
            ORDER BY job_id, created_at DESC
        )
        SELECT
            j.job_id,
            j.job_number,
            j.job_name,
            j.job_description,
            j.status,
            j.priority,
            j.scheduled_start_date,
            j.scheduled_end_date,
            j.actual_start_date,
            j.actual_end_date,
            j.job_type,
            j.job_category,
            j.vendor_name,
            j.site_address_city as site_city,
            j.site_address_state as site_state,
            COUNT(DISTINCT ja.contractor_id) as assigned_contractors,
            COUNT(DISTINCT sv.visit_id) as total_visits,
            MAX(sv.check_in_time) as last_check_in,
            COUNT(DISTINCT i.issue_id) FILTER (
                WHERE i.issue_status NOT IN ('resolved', 'closed')
            ) as open_issues,
            COALESCE(lp.completion_percentage_after, 0)
                as current_completion_percentage,
            COUNT(DISTINCT t.task_id) FILTER (
                WHERE t.task_status != 'completed'
            ) as pending_tasks,
            COUNT(DISTINCT t.task_id) as total_tasks,
            CASE
                WHEN jc.job_completed THEN 'Completed'
                WHEN j.actual_start_date IS NOT NULL THEN 'In Progress'
                ELSE 'Not Started'
            END as progress_status,
            jc.vendor_confirmed,
            jc.vendor_confirmed_at,
            j.vendor_sync_status
        FROM jobs j
        LEFT JOIN job_assignments ja ON j.job_id = ja.job_id
            AND ja.assignment_status = 'active'
        LEFT JOIN site_visits sv ON j.job_id = sv.job_id
        LEFT JOIN issues i ON j.job_id = i.job_id
        LEFT JOIN tasks t ON j.job_id = t.job_id
        LEFT JOIN job_completions jc ON j.job_id = jc.job_id
        LEFT JOIN latest_progress lp ON j.job_id = lp.job_id
        WHERE j.deleted_at IS NULL
        GROUP BY j.job_id, j.job_number, j.job_name, j.job_description,
                 j.status, j.priority, j.scheduled_start_date,
                 j.scheduled_end_date, j.actual_start_date,
                 j.actual_end_date, j.job_type, j.job_category,
                 j.vendor_name, j.site_address_city, j.site_address_state,
                 jc.job_completed, lp.completion_percentage_after,
                 lp.last_progress_update, jc.vendor_confirmed,
                 jc.vendor_confirmed_at, j.vendor_sync_status;
    """)

    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_index('idx_photos_photo_location', postgresql_using='gist')

    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('local_sync_queue', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('idx_jobs_job_location_geography', postgresql_using='gist')
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('job_responses', schema=None) as batch_op:
        batch_op.drop_constraint('unique_job_contractor_response', type_='unique')
        batch_op.drop_index('idx_job_responses_job_accepted_location', postgresql_using='gist')
        batch_op.create_unique_constraint('job_responses_job_id_contractor_id_key', ['job_id', 'contractor_id'])
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('job_completions', schema=None) as batch_op:
        batch_op.drop_constraint('job_completions_job_id_key', type_='unique')
        batch_op.drop_index('idx_job_completions_job_completed_location', postgresql_using='gist')
        batch_op.create_unique_constraint('job_completions_job_id_contractor_id_key', ['job_id', 'contractor_id'])
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('job_assignments', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_constraint('issues_assigned_contractor_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('issues_contractor_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('issues_contractor_id_fkey', 'contractors', ['contractor_id'], ['contractor_id'], ondelete='CASCADE')
        batch_op.drop_index('idx_issues_issue_reported_location', postgresql_using='gist')
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('contractor_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_column('assigned_contractor_id')

    with op.batch_alter_table('contractors', schema=None) as batch_op:
        batch_op.drop_index('idx_contractors_email', postgresql_where=sa.text('deleted_at IS NULL'))
        batch_op.create_index('idx_contractors_email', ['email'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('contractor_sessions', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('session_duration_minutes')

    with op.batch_alter_table('contractor_insurance', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('contractor_devices', schema=None) as batch_op:
        batch_op.drop_constraint('unique_contractor_device', type_='unique')
        batch_op.create_unique_constraint('contractor_devices_contractor_id_device_id_key', ['contractor_id', 'device_id'])
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('contractor_credentials', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('biometric_verifications', schema=None) as batch_op:
        batch_op.drop_index('idx_biometric_verifications_location', postgresql_using='gist')

    # ### end Alembic commands ###
