"""empty message

Revision ID: 84806d24e503
Revises: 6b880abb4c9a
Create Date: 2026-03-22 21:21:49.493345

"""

from alembic import op
import sqlalchemy as sa
from app.models.types import PercentValue
from sqlalchemy.schema import FetchedValue


# revision identifiers, used by Alembic.
revision = '84806d24e503'
down_revision = '6b880abb4c9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###e dropped independently
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('idx_audit_contractor', ['contractor_id', 'changed_at'], unique=False)
        batch_op.create_index('idx_audit_record', ['table_name', 'record_id', 'changed_at'], unique=False)

    with op.batch_alter_table('contractors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('company_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('employee_id', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint(None, ['username'])

    with op.batch_alter_table('local_sync_queue', schema=None) as batch_op:
        batch_op.create_index('idx_local_sync_contractor', ['contractor_id', 'sync_status', 'created_at'], unique=False)
        batch_op.create_index('idx_local_sync_status', ['sync_status', 'next_attempt_at', 'priority'], unique=False, postgresql_where=sa.text("sync_status = 'pending'"))

    with op.batch_alter_table('progress_updates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completion_percentage_after', PercentValue(), server_default=FetchedValue(), nullable=True))

    with op.batch_alter_table('vendor_sync_queue', schema=None) as batch_op:
        batch_op.create_index('idx_vendor_sync_entity', ['entity_type', 'vendor_entity_id'], unique=False, postgresql_where=sa.text('vendor_entity_id IS NOT NULL'))
        batch_op.create_index('idx_vendor_sync_status', ['vendor_id', 'sync_status', 'next_attempt_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_sync_queue', schema=None) as batch_op:
        batch_op.drop_index('idx_vendor_sync_status')
        batch_op.drop_index('idx_vendor_sync_entity', postgresql_where=sa.text('vendor_entity_id IS NOT NULL'))

    with op.batch_alter_table('progress_updates', schema=None) as batch_op:
        batch_op.drop_column('completion_percentage_after')

    with op.batch_alter_table('local_sync_queue', schema=None) as batch_op:
        batch_op.drop_index('idx_local_sync_status', postgresql_where=sa.text("sync_status = 'pending'"))
        batch_op.drop_index('idx_local_sync_contractor')

    with op.batch_alter_table('contractors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('employee_id')
        batch_op.drop_column('company_name')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('username')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_record')
        batch_op.drop_index('idx_audit_contractor')

    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
